# Generated by Django 2.0.6 on 2018-06-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dietary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('response', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='registryPictures/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('raised', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.RSVP'),
        ),
        migrations.AddField(
            model_name='dietary',
            name='guest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.Guest'),
        ),
    ]
