# Generated by Django 2.0.6 on 2018-07-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_auto_20180731_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='code',
        ),
        migrations.AddField(
            model_name='guest',
            name='plusone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='rsvp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RSVP',
        ),
    ]
