# Generated by Django 2.0.6 on 2018-07-31 16:09

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('wedding', '0004_auto_20180731_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='id',
            new_name='guestid',
        ),
    ]
