# Generated by Django 2.0.6 on 2018-08-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_auto_20180731_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dietary',
            unique_together={('guest_id', 'restriction')},
        ),
    ]
