# Generated by Django 2.0.6 on 2018-08-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_auto_20180807_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
