# Generated by Django 2.0.6 on 2018-08-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0007_guest_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.Registry')),
            ],
        ),
    ]
