# Generated by Django 2.0.6 on 2018-08-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0008_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='code',
            field=models.CharField(default='a', max_length=4, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registry',
            name='raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
