# Generated by Django 2.0.6 on 2018-08-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0010_auto_20180822_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
