# Generated by Django 2.0.6 on 2018-08-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0011_contribution_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
