# Generated by Django 2.0.6 on 2018-08-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0012_contribution_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='game',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='tea',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
