# Generated by Django 2.0.6 on 2019-01-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0013_auto_20180827_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='restrictions',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
