# Generated by Django 2.0.6 on 2019-02-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0014_guest_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='category',
            field=models.CharField(blank=True, choices=[('F', 'Furniture'), ('G', 'Games'), ('H', 'House'), ('K', 'Kitchen'), ('T', 'Travel'), ('Z', 'Other')], max_length=1),
        ),
    ]
