# Generated by Django 2.0.6 on 2019-02-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0016_auto_20190206_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'Kitchen'), ('B', 'Furniture'), ('C', 'House'), ('D', 'Games'), ('E', 'Travel'), ('Z', 'Other')], max_length=1),
        ),
    ]
